### ISSUE TITLE
Why does send_get_emails_request retry when no emails are found? 

### ISSUE THREAD

**Issue by tk8817** [mailosaurapp/mailosaur-ruby#9]
Hey @mailosaurapp, 

We are calling  get_emails_by_recipient for an inbox and then checking the results, but we noticed that if the inbox is empty, send_get_emails_request will keep retrying for @timeout seconds (default 20). This seems inconsistent, because the method returns instantly when the inbox does have mails. We would expect instead that the method return null/0/'no results', etc. 

Why is the current design bad for us? Well, we are looking for a specific new email when we check an inbox - so if you block for 20 seconds on each attempt, that adds a tonne of time to our ownloop which is retrying / looking for this email. If we remove our loop and only check once (but there is an existing email in the inbox) then we most likely will only get older emails, not the newest one. 

```ruby
  inbox   = Magic.username
  subject = FigNewton.send("email_#{type}")
  10.times do | i |
    emails = @mailbox.get_emails_by_recipient(inbox)

    if emails.is_a?(Array) && emails.map(&:subject).include?(subject)
      puts 'found mail'
      break
    else
      sleep(2)
      puts 'no mail found' if i == 9
    end
  end
```

Any thoughts?

**Comment by mailosaurapp** [comment]
Hi Justin,

I've sent you a message through our support. The reason there is a delay and repeat in there is because there can be some time between sending the email and it being available in Mailosaur.

Thanks,

Andy

**Comment by tk8817** [comment]
Hi @mailosaurapp -- we fully understand that there can be a delay, but this should be handled by the folks using your library, not you. The reason is that your point about  'waiting for an email' only applies to empty inboxes, and this causes divergent behaviour when dealing with inboxes that are not empty.

Folks who use your library will always have to build a loop around their inbox lookup for cases where the inbox already has emails, and you are waiting for a new one. Your current code of retrying empty inboxes, causes the developers self built loop to then become very slow / wonky.

**Comment by tk8817** [comment]
@mailosaurapp also this affects our testing for empty inboxes where we specifically are checking to ensure an email was NOT received. :(

**Comment by mailosaurapp** [comment]
Hi @tk8817,

Thanks for the pull requests. What you're saying about checking for not receiving an email makes sense and would indeed cause issue with how the timeouts are implemented.

I've merged your proper PR and will be creating a new Gem.

Hope that helps,

thanks

**Comment by tk8817** [comment]
Big thanks for the fast turnaround @mailosaurapp , you guys have been really solid with responding and merging. We bought a full year subscription and look forward to seeing what new stuff you cook up.

**Comment by mailosaurapp** [comment]
An updated gem is now available: https://rubygems.org/gems/mailosaur/versions/0.1.1
